
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: wildlife_tracker_development

test:
  <<: *default
  database: wildlife_tracker_test

production:
  <<: *default
  database: wildlife_tracker_production
  username: wildlife_tracker
  password: <%= ENV['WILDLIFE_TRACKER_DATABASE_PASSWORD'] %>
