# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efcf9b89964df928caf91d8b4cbbac4fa778aabf8278ea6001e75f6bdb3a5bfd7a58bf316f49562121dab92eccbb1c720fec366d935de83bfc9960d15532c17f

test:
  secret_key_base: a50f78d98b4e34a30c1779fbcecee21010d09bd248b1ca32ccc02cc3e19cf7604457f72c058c037ba37f7d1da5ceb959af6ebc55f091ca491afec7ae1b4efdf2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
